/*
  Warnings:

  - The values [CSHARE] on the enum `TechnologyType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "TechnologyType_new" AS ENUM ('REACT', 'VUE', 'ANGULAR', 'SVELTE', 'NEXT', 'NUXT', 'GATSBY', 'ASTRO', 'REMIX', 'SOLID', 'PREACT', 'QWIK', 'REACT_NATIVE', 'FLUTTER', 'KOTLIN', 'SWIFT', 'IONIC', 'XAMARIN', 'CORDOVA', 'CAPACITOR', 'NODE', 'EXPRESS', 'NEST', 'FASTIFY', 'KOA', 'DJANGO', 'FLASK', 'FASTAPI', 'SPRING_BOOT', 'LARAVEL', 'SYMFONY', 'RAILS', 'PHOENIX', 'ACTIX', 'ROCKET', 'JAVASCRIPT', 'TYPESCRIPT', 'PYTHON', 'JAVA', 'GO', 'RUST', 'CPP', 'CSHARP', 'PHP', 'RUBY', 'ELIXIR', 'SCALA', 'KOTLIN_JVM', 'DART', 'R', 'JULIA', 'POSTGRESQL', 'MYSQL', 'MONGODB', 'REDIS', 'CASSANDRA', 'DYNAMODB', 'FIREBASE', 'SUPABASE', 'PLANETSCALE', 'COCKROACHDB', 'ELASTICSEARCH', 'NEO4J', 'INFLUXDB', 'TIMESCALEDB', 'AWS', 'AZURE', 'GCP', 'VERCEL', 'NETLIFY', 'RAILWAY', 'RENDER', 'FLY_IO', 'DIGITAL_OCEAN', 'HEROKU', 'CLOUDFLARE', 'DOCKER', 'KUBERNETES', 'TERRAFORM', 'ANSIBLE', 'JENKINS', 'GITHUB_ACTIONS', 'GITLAB_CI', 'CIRCLECI', 'TRAVIS_CI', 'TENSORFLOW', 'PYTORCH', 'SCIKIT_LEARN', 'KERAS', 'HUGGING_FACE', 'LANGCHAIN', 'OPENAI', 'ANTHROPIC', 'STABLE_DIFFUSION', 'ETHEREUM', 'SOLIDITY', 'WEB3_JS', 'ETHERS', 'HARDHAT', 'TRUFFLE', 'POLYGON', 'SOLANA', 'JEST', 'VITEST', 'CYPRESS', 'PLAYWRIGHT', 'SELENIUM', 'PYTEST', 'JUNIT', 'TAILWIND', 'MATERIAL_UI', 'CHAKRA_UI', 'SHADCN', 'STYLED_COMPONENTS', 'EMOTION', 'SASS', 'REDUX', 'ZUSTAND', 'MOBX', 'RECOIL', 'JOTAI', 'PINIA', 'VITE', 'WEBPACK', 'TURBOPACK', 'ESBUILD', 'ROLLUP', 'PARCEL', 'GRAPHQL', 'REST_API', 'GRPC', 'WEBSOCKETS', 'SOCKET_IO', 'STRIPE', 'TWILIO', 'SENDGRID', 'PRISMA', 'DRIZZLE', 'TYPEORM');
ALTER TABLE "StartupInfo" ALTER COLUMN "technologies" TYPE "TechnologyType_new"[] USING ("technologies"::text::"TechnologyType_new"[]);
ALTER TYPE "TechnologyType" RENAME TO "TechnologyType_old";
ALTER TYPE "TechnologyType_new" RENAME TO "TechnologyType";
DROP TYPE "public"."TechnologyType_old";
COMMIT;
