-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('STARTUP', 'COMPANY', 'ADMIN');

-- CreateEnum
CREATE TYPE "TechnologyType" AS ENUM ('REACT', 'NODE', 'TYPESCRIPT', 'PYTHON', 'DJANGO', 'REACT_NATIVE', 'FLUTTER', 'KOTLIN', 'SWIFT', 'GO', 'JAVASCRIPT', 'CPP', 'CSHARE');

-- CreateEnum
CREATE TYPE "IndustryType" AS ENUM ('FINTECH', 'EDTECH', 'HEALTHTECH', 'BIOTECH', 'AGRITECH', 'PROPTECH', 'INSURTECH', 'LEGALTECH', 'HRTECH', 'MARTECH', 'ADTECH', 'CYBERSECURITY', 'BLOCKCHAIN', 'WEB3', 'CRYPTO', 'ARTIFICIAL_INTELLIGENCE', 'MACHINE_LEARNING', 'CLOUD_COMPUTING', 'SAAS', 'ECOMMERCE', 'MARKETPLACE', 'MOBILITY', 'LOGISTICS', 'DELIVERY', 'TRANSPORTATION', 'AUTOMOTIVE', 'ELECTRIC_VEHICLES', 'AUTONOMOUS_VEHICLES', 'CLEANTECH', 'ENERGY', 'RENEWABLE_ENERGY', 'SUSTAINABILITY', 'CLIMATE_TECH', 'GREENTECH', 'CIRCULAR_ECONOMY', 'HEALTHCARE', 'TELEHEALTH', 'MENTAL_HEALTH', 'FITNESS', 'WELLNESS', 'PHARMACEUTICALS', 'MEDICAL_DEVICES', 'BANKING', 'PAYMENTS', 'LENDING', 'INVESTMENT', 'WEALTH_MANAGEMENT', 'EDUCATION', 'ONLINE_LEARNING', 'CORPORATE_TRAINING', 'LANGUAGE_LEARNING', 'ENTERTAINMENT', 'GAMING', 'STREAMING', 'SOCIAL_MEDIA', 'CONTENT_CREATION', 'MUSIC', 'SPORTS', 'FOODTECH', 'RESTAURANT_TECH', 'FOOD_DELIVERY', 'MEAL_KITS', 'AGRICULTURE', 'RETAIL', 'FASHION', 'BEAUTY', 'CONSUMER_GOODS', 'DIRECT_TO_CONSUMER', 'REAL_ESTATE', 'CONSTRUCTION', 'SMART_HOME', 'COWORKING', 'FUTURE_OF_WORK', 'PRODUCTIVITY', 'COLLABORATION', 'RECRUITING', 'FREELANCE_PLATFORMS', 'IOT', 'HARDWARE', 'ROBOTICS', 'DRONES', 'WEARABLES', 'TRAVEL', 'TOURISM', 'HOSPITALITY', 'TELECOMMUNICATIONS', 'MESSAGING', 'VIDEO_CONFERENCING', 'MANUFACTURING', 'INDUSTRY_4_0', 'SUPPLY_CHAIN', 'SPACE_TECH', 'NANOTECHNOLOGY', 'QUANTUM_COMPUTING', 'VIRTUAL_REALITY', 'AUGMENTED_REALITY', 'API_TOOLS', 'DEVELOPER_TOOLS', 'DATA_ANALYTICS', 'BUSINESS_INTELLIGENCE', 'OTHER');

-- CreateEnum
CREATE TYPE "CompanyType" AS ENUM ('VENTURE_CAPITAL', 'ANGEL_INVESTOR', 'ACCELERATOR', 'CORPORATION', 'STARTUP', 'GOVERNMENT', 'OTHER');

-- CreateEnum
CREATE TYPE "PositionType" AS ENUM ('CEO', 'CO_FOUNDER', 'UX_DESIGNER', 'UI_DESIGNER', 'PRODUCT_DESIGNER', 'PRODUCT_MANAGER', 'SOFTWARE_ENGINEER', 'FRONTEND_DEVELOPER', 'BACKEND_DEVELOPER', 'FULLSTACK_DEVELOPER', 'MOBILE_DEVELOPER', 'DEVOPS_ENGINEER', 'DATA_ENGINEER', 'ML_ENGINEER', 'SECURITY_ENGINEER', 'DATA_SCIENTIST', 'MARKETING_MANAGER', 'SALES_MANAGER', 'CONTENT_MANAGER', 'OTHER');

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" "UserRole" NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "logo" TEXT,
    "webiste" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StartupInfo" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "foundedYear" INTEGER NOT NULL,
    "industry" "IndustryType" NOT NULL,
    "technologies" "TechnologyType"[],
    "pitchDeck" TEXT,
    "demoVideo" TEXT NOT NULL,
    "monthlyUsersAverage" INTEGER,
    "revenue" INTEGER,
    "teamSize" INTEGER NOT NULL,
    "visible" BOOLEAN NOT NULL DEFAULT false,
    "github" TEXT,
    "instagram" TEXT,
    "linkedin" TEXT,
    "facebook" TEXT,

    CONSTRAINT "StartupInfo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CompanyInfo" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "industry" "IndustryType" NOT NULL,
    "size" TEXT NOT NULL,
    "companyType" "CompanyType" NOT NULL,
    "website" TEXT,

    CONSTRAINT "CompanyInfo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Member" (
    "id" SERIAL NOT NULL,
    "startupInfoId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "age" INTEGER NOT NULL,
    "position" "PositionType" NOT NULL,
    "profileImage" TEXT,
    "university" TEXT,

    CONSTRAINT "Member_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "User_name_key" ON "User"("name");

-- CreateIndex
CREATE UNIQUE INDEX "StartupInfo_userId_key" ON "StartupInfo"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "CompanyInfo_userId_key" ON "CompanyInfo"("userId");

-- AddForeignKey
ALTER TABLE "StartupInfo" ADD CONSTRAINT "StartupInfo_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CompanyInfo" ADD CONSTRAINT "CompanyInfo_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Member" ADD CONSTRAINT "Member_startupInfoId_fkey" FOREIGN KEY ("startupInfoId") REFERENCES "StartupInfo"("id") ON DELETE CASCADE ON UPDATE CASCADE;
